name: retrofit_sandbox
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.4
  retrofit: ^4.0.1
  dio: ^5.1.1
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.4
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^6.0.0+1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.6
  freezed: ^2.3.2

flutter:
  uses-material-design: true